=== OpenShift Local

Follow the instructions on https://www.openshift.org[Try Origin,window=_blank]. We use the https://www.openshift.org/vm[all-in-one VM,window=_blank] approach through a Vagrant VirtualBox VM

After you have installed Vagrant and VirtualBox, run:

```
$ vagrant init openshift/origin-all-in-one
$ vagrant up --provider=virtualbox
...
Successfully started and provisioned VM with 2 cores and 5 G of memory.
To modify the number of cores and/or available memory modify your local Vagrantfile
```

You can now access the OpenShift console on: https://10.2.2.2:8443/console[https://10.2.2.2:8443/console,window=_blank]

Configured users are:

```
admin/admin
user/user
```

This should now allow you to ssh into the VM

```
$ vagrant ssh
Last login: Mon Feb  8 09:06:26 2016 from 10.0.2.2
```

and use the OpenShift command line client.

==== Client Tools

The client tools are available https://10.2.2.2:8443/console/command-line[from the console,window=_blank].

==== Docker access 

The docker deamon running in the Vagrant VM needs be exposed on the network. 
Add these deamon options to the original OpenShift docker config.

```
[vagrant@localhost ~]$ sudo vi /etc/sysconfig/docker
# Additional startup options for the Docker daemon
OPTIONS="-H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock"
```

Then restart the docker deamon 

```
[vagrant@localhost ~]$ sudo systemctl restart docker
```

On you local machine, setup route to the Vagrant VM

```
$ sudo cat /etc/hosts
10.2.2.2    origin
```

and a few Docker related environment variables for the project maven build

```
export DOCKER_HOST=tcp://origin:2375
export DOCKER_IP=origin
```

Port forwarding must be enabled in the Vagrantfile.

```
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 8443, host: 8443
  config.vm.network "forwarded_port", guest: 2375, host: 2375
```